name: Playwright FB

on:
  # schedule:
  #   - cron: "*/5 * * * *"
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Install dependencies
        run: pnpm i -f --fix-lockfile

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps

      - name: Set up Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -ac -screen 0 1920x1080x24 &
        env:
          DISPLAY: :99

      - name: Run Playwright
        run: pnpm exec playwright test tests/fb.spec.ts
        env:
          XS: ${{ secrets.XS }}
          DISPLAY: :99

      # push to repo
      - name: Commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Automated commit"
          git push

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
