name: Playwright Tests

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: oven-sh/setup-bun@main
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i -f

      - name: Install Playwright Browsers
        run: bun run playwright install --with-deps

      - name: Set up Xvfb
        run: sudo apt-get install -y xvfb

      - name: Start Xvfb
        run: Xvfb :99 -ac -screen 0 1280x1024x24 &
        env:
          DISPLAY: :99

      - name: Run Playwright tests
        run: bun run playwright test tests/movie.spec.ts
        env:
          DO_URL: ${{ secrets.DO_URL }}
          DISPLAY: :99

      - uses: actions/upload-artifact@main
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
